# # Содержимое файла куки
# content = """# Netscape HTTP Cookie File
# # https://curl.se/docs/http-cookies.html
# # This file was generated by libcurl! Edit at your own risk.
#
# www.copart.com	FALSE	/	FALSE	0	incap_ses_1574_242093	fxgoPlQaARInLiyUHfnXFbyOFmUAAAAAkATQKQzhDEkZKsea11XWIg==
# #HttpOnly_www.copart.com	FALSE	/	FALSE	1727476622	visid_incap_242093	kTbLU6mFRqySnjX704xXDbyOFmUAAAAAQUIPAAAAAAADWECSsahSOkGAxGnxu+8M"""
#
# # Извлечение куки из содержимого
# lines = content.split('\n')
# cookies = {}
# for line in lines:
#     parts = line.split('\t')
#     if len(parts) == 7:
#         domain, _, _, _, _, key, value = parts
#         if key.startswith('incap_ses'):
#             cookies[key] = value

# print(cookies)

import requests
headers = {
    'authority': 'www.copart.com',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'ru,en-US;q=0.9,en;q=0.8,uk;q=0.7,de;q=0.6',
    'cache-control': 'no-cache',
    # 'cookie': 'nlbi_242093=osq3MECFUlTHAvJFJDHybgAAAACs3SynhghI19ueF6oKCKdV; timezone=Europe%2FKiev; userCategory=RPU; userLang=ru; g2app.search-table-rows=20; visid_incap_242093=5V8EJaQkQ3ScwSP6sYV8Jb6WDGUAAAAARkIPAAAAAACAVlGvAcEY3SKQOEtHMGI0zgKZJWm3T/12; g2usersessionid=c5b2569f1ff735589559c3b0f42c764e; copartTimezonePref=%7B%22displayStr%22%3A%22GMT%2B3%22%2C%22offset%22%3A3%2C%22dst%22%3Atrue%2C%22windowsTz%22%3A%22Europe%2FKiev%22%7D; incap_sh_242093=RMQXZQAAAAA7Ho5tBgAQxIjfqAY+1qgWFI5BWPdI7mEB2xbI; G2JSESSIONID=1BAEED8862AEBCFDEA94F127C1AA437B-n1; nlbi_242093_2147483392=jnjbIUd9EhapheQEJDHybgAAAACKrdRupgmsiqhbpiv5kdDW; incap_ses_325_242093=DL02YdRfLVZhdwIteKKCBB7KF2UAAAAAiEHPAnXvT3R1+cxe4Ax9BQ==; reese84=3:+QvWAX7Sjc1UWpDm7cyXNg==:zXzTd+d7ZiBkkguWKUVFxBjoYThguWG/xVevpYXIGHVvKKsjlKyrQU1boink13Ge4WlsIqqzD3EVSJpYIp7MECJy5dIXIF1ZXQlQfQGlNM0bXo5upXXRGNSQtgwmIfaNY1cB8fJQRrrO6DKahakqdC1ZtI96YzxLwqGzj+URdjftV9Qet7DFr3eImut6v4Cv3p0VdJT7mvpDNE7LZIW8B6PacMh5rkMNZ8RGBECOYljaJwjeM3nJruviwER8oD00HhQCyovB33dPm3+O1ogyZEHoADEfT2ge4w8W/ObiLyx1o05phpUEzKeEzQB1G77SuZQKDqQ3Kw2xJFMJ6CFFibRsKGj/wvQsfl6b2REN+JuUF1uWKmEECPcKKsPWoWlwGQExzJJYP1Z7RK09CLq1d35UZ9Bb/y2ay3ff8gfD8cAt+0POwALnnYYnq1IScuPYrrnsYlp611ZVrRR5j/Ab7nDIAbu3PAyI6HTOqCd/emG9O95BFLXQG2lhk9McwX2C:Knth1bQBmOdIxgN4TfIlMZOaMmfyIFqufJsTw/H+ruo=',
    'dnt': '1',
    'pragma': 'no-cache',
    'referer': 'https://www.copart.com/vehicleFinderSearch?displayStr=%5B0%20TO%209999999%5D,%5B2011%20TO%202024%5D&from=%2FvehicleFinder&searchCriteria=%7B%22query%22:%5B%22*%22%5D,%22filter%22:%7B%22NLTS%22:%5B%22expected_sale_assigned_ts_utc:%5BNOW%2FDAY-1DAY%20TO%20NOW%2FDAY%5D%22%5D%7D,%22searchName%22:%22%22,%22watchListOnly%22:false,%22freeFormSearch%22:false%7D',
    'sec-ch-ua': '"Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
}
session = requests.Session()

session.headers.update(headers)
# Отправляем GET-запрос на веб-сайт
response = session.get('https://www.copart.com/vehicleFinderSearch?displayStr=%5B0%20TO%209999999%5D,%5B2011%20TO%202024%5D&from=%2FvehicleFinder&searchCriteria=%7B%22query%22:%5B%22*%22%5D,%22filter%22:%7B%22NLTS%22:%5B%22expected_sale_assigned_ts_utc:%5BNOW%2FDAY-1DAY%20TO%20NOW%2FDAY%5D%22%5D%7D,%22searchName%22:%22%22,%22watchListOnly%22:false,%22freeFormSearch%22:false%7D')

# Куки будут автоматически сохранены в сессии
# Вы можете получить их следующим образом
cookies = session.cookies.get_dict()

# Теперь у вас есть словарь с куками, который вы можете использовать в дальнейших запросах
print(cookies)